# Generated by Django 5.1.5 on 2025-04-17 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemaapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_type', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='cinemaapp.review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinemaapp.register')),
            ],
            options={
                'unique_together': {('review', 'user')},
            },
        ),
    ]
